import os
import sys
import subprocess
import time

# Force stdout to UTF-8 for Windows console support
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

QUERIES_FILE = "queries.txt"
COMPLETED_FILE = "completed_queries.txt"
RESULTS_FILE = "results.csv"
TEMP_QUERY_FILE = "_temp_query.txt"
TEMP_RESULTS_FILE = "_query_out.csv"

def check_results_file_unlocked():
    if not os.path.exists(RESULTS_FILE):
        return True
    try:
        with open(RESULTS_FILE, "a", encoding="utf-8"):
            pass
        return True
    except PermissionError:
        return False

def merge_query_out_into_master():
    """
    Safely reads _query_out.csv generated by scraper executable and 
    appends all new leads into master results.csv without EVER truncating results.csv.
    """
    if not os.path.exists(TEMP_RESULTS_FILE):
        return 0

    try:
        with open(TEMP_RESULTS_FILE, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
    except Exception as e:
        print(f"[ERROR] Failed to read scraper output file: {e}")
        return 0

    if not lines:
        return 0

    # Filter out empty lines
    lines = [line for line in lines if line.strip()]
    if not lines:
        return 0

    header = lines[0]
    data_rows = lines[1:]

    # Check if master results.csv exists and has content
    master_exists = os.path.exists(RESULTS_FILE) and os.path.getsize(RESULTS_FILE) > 0

    lines_to_append = []
    if not master_exists:
        # Write header first, then data rows
        lines_to_append = [header] + data_rows
    else:
        # Append data rows only (skip duplicate header)
        lines_to_append = data_rows

    if lines_to_append:
        with open(RESULTS_FILE, "a", encoding="utf-8") as master:
            master.writelines(lines_to_append)

    # Clean up temp file
    try:
        os.remove(TEMP_RESULTS_FILE)
    except Exception:
        pass

    return len(data_rows)

def load_queries():
    if not os.path.exists(QUERIES_FILE):
        print(f"Error: {QUERIES_FILE} not found!")
        return []
    with open(QUERIES_FILE, "r", encoding="utf-8") as f:
        return [line.strip() for line in f if line.strip()]

def load_completed():
    if not os.path.exists(COMPLETED_FILE):
        return set()
    with open(COMPLETED_FILE, "r", encoding="utf-8") as f:
        return set(line.strip() for line in f if line.strip())

def mark_completed(query):
    with open(COMPLETED_FILE, "a", encoding="utf-8") as f:
        f.write(query + "\n")

def main():
    queries = load_queries()
    completed = load_completed()
    pending = [q for q in queries if q not in completed]

    total = len(queries)
    done_count = len(completed)
    remaining = len(pending)

    print("=" * 60)
    print("  Google Maps Scraper - Smart Batch Runner")
    print(f"  Total queries: {total}")
    print(f"  Already completed: {done_count}")
    print(f"  Remaining to scrape: {remaining}")
    print("=" * 60)

    if not pending:
        print("\nAll queries in queries.txt have already been completed!")
        print("To start over, delete 'completed_queries.txt' and 'results.csv'.")
        return

    # Ensure master results.csv file is not locked by Excel before starting
    while not check_results_file_unlocked():
        print(f"\n[WARNING] {RESULTS_FILE} is currently OPEN in another program (like Excel).")
        print(f"Please CLOSE {RESULTS_FILE} so the scraper can append leads to it.")
        print("Retrying in 5 seconds... (Press Ctrl+C to cancel)")
        time.sleep(5)

    for idx, query in enumerate(pending, start=1):
        while not check_results_file_unlocked():
            print(f"\n[WARNING] {RESULTS_FILE} is locked by Excel/editor. Please close it.")
            time.sleep(5)

        print(f"\n[{idx}/{remaining}] Processing: \"{query}\"...")

        # Clean old temp output file if left over
        if os.path.exists(TEMP_RESULTS_FILE):
            try:
                os.remove(TEMP_RESULTS_FILE)
            except Exception:
                pass

        # Write single query file for scraper executable
        with open(TEMP_QUERY_FILE, "w", encoding="utf-8") as f:
            f.write(query + "\n")

        cmd = [
            ".\\google_maps_scraper.exe",
            "-input", TEMP_QUERY_FILE,
            "-results", TEMP_RESULTS_FILE,
            "-depth", "2",
            "-email",
            "-exit-on-inactivity", "1m"
        ]

        try:
            # Run scraper executable for this query
            proc = subprocess.run(cmd)

            # Safely merge leads into master results.csv
            added_count = merge_query_out_into_master()

            if added_count > 0:
                mark_completed(query)
                print(f"[DONE] \"{query}\" -> Appended {added_count} leads to {RESULTS_FILE} & marked completed.")
            else:
                print(f"[RETRY NEEDED] \"{query}\" -> 0 leads extracted. Query NOT marked completed.")

        except KeyboardInterrupt:
            print("\n\n[PAUSED] Stopped by user! Progress saved in completed_queries.txt.")
            print("Run 'python run_scraper.py' anytime to resume where you left off.")
            if os.path.exists(TEMP_QUERY_FILE):
                os.remove(TEMP_QUERY_FILE)
            if os.path.exists(TEMP_RESULTS_FILE):
                os.remove(TEMP_RESULTS_FILE)
            sys.exit(0)
        except Exception as e:
            print(f"Error processing query \"{query}\": {e}")

    if os.path.exists(TEMP_QUERY_FILE):
        os.remove(TEMP_QUERY_FILE)

    print("\n🎉 All remaining queries finished successfully!")

if __name__ == "__main__":
    main()
